version: "3.3"

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    command: "sh -c 'dotnet /app/Ecommerce.Api.dll'"
    ports:
      - "${PORT}:80"
    environment:
      - ConnectionStrings__SqlServerString=Server=db;Database=EcommerceApp;User Id=sa;Password=kDFJKSHIUE86432sfd;Encrypt=True;TrustServerCertificate=true
      - JWTOptions__SecretKey=random-key-is-here
      - JWTOptions__validIssuer=Ecommerce-Api
      - JWTOptions__validAudience=Ecommerce-Api-Client
      - JWTOptions__expires=60
      - IpRateLimiting__EnableEndpointRateLimiting=false
      - IpRateLimiting__StackBlockedRequests=false
      - IpRateLimiting__RealIpHeader=X-Real-IP
      - IpRateLimiting__ClientIdHeader=X-ClientId
      - IpRateLimiting__HttpStatusCode=429
      - IpRateLimiting__IpWhitelist=
      - IpRateLimiting__EndpointWhitelist=get:/api/whaterehere
      - IpRateLimiting__ClientWhitelist=
      - IpRateLimiting__GeneralRules__0__Endpoint=*
      - IpRateLimiting__GeneralRules__0__Period=1m
      - IpRateLimiting__GeneralRules__0__Limit=25
      - IpRateLimiting__IpRateLimitPolicies__IpRules__0__Ip=127.0.0.1
      - IpRateLimiting__IpRateLimitPolicies__IpRules__0__Rules__0__Endpoint=*
      - IpRateLimiting__IpRateLimitPolicies__IpRules__0__Rules__0__Period=1m
      - IpRateLimiting__IpRateLimitPolicies__IpRules__0__Rules__0__Limit=25
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "kDFJKSHIUE86432sfd"
    expose:
      - "${DB_PORT}"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
