version: "3.3"

services:
  ecommerce:
    build:
      context: .
      dockerfile: Dockerfile
    command: "sh -c 'dotnet /app/Ecommerce.Api.dll'"
    ports:
      - "${PORT}:80"
    environment:
      Kestrel__Endpoints__Urls__Url: "http://0.0.0.0:80"
      ConnectionStrings__SqlServerString: "Server=${DB_HOST},${DB_PORT};Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASSWORD};Encrypt=True;TrustServerCertificate=True;"
      JWTOptions__SecretKey: ${SECRET_KEY}
      JWTOptions__validIssuer: ${JWT_ISSUER}
      JWTOptions__validAudience: ${JWT_AUDIENCE}
      JWTOptions__issuerSigningKey: ${SECRET_KEY}
      RealIpHeader: "X-Real-IP"
      ForwardedForHeader: "X-Forwarded-For"
      ClientIpHeader: "X-Client-IP"
      AllowedHosts: "*"
      EnableEndpointRateLimiting: false
      StackBlockedRequests: false
      StackBlockedRequestsTime: 60
      StackBlockedRequestsMax: 20
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
      MSSQL_PID: "Express"
    expose:
      - "${DB_PORT}"
    volumes:
      - dbdata:/var/opt/mssql

volumes:
  dbdata:
