name: Build, Test and Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker hub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.USERNAME }}/ecommerce-webapi:latest

  deploy:
    needs: build
    name: Deploy to server
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull ${{ secrets.USERNAME }}/ecommerce-webapi:latest
            docker container stop ecommerce-webapi
            docker container prune -f
            docker run -d --name ecommerce-webapi -p 80:80 -p 443:443 ${{ secrets.USERNAME }}/ecommerce-webapi:latest
            docker image prune -f
