# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker hub login
        uses: docker/login-action@v3
        with:
          username: {{secrets.USERNAME}}
          password: {{secrets.PASSWORD}}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: {{secrets.USERNAME}}/ecommerce-webapi:latest
